name: Use Artifacts and Build

on:
 workflow_dispatch
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: all-jar-artifacts
        path: jar-artifacts

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Downloaded Artifacts
      run: |
        # You can now use the JAR files in the 'jar-artifacts/' directory
        # for your Maven build or any other necessary tasks.
        mvn clean install -f jar-artifacts/your-module/pom.xml
